# Copyright (c) Meta Platforms, Inc. and affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

name: CI

on: [push, pull_request]

jobs:
  rust-lint:
    name: Rust Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2022-06-26
          override: true
          components: rustfmt
      - name: "rustfmt"
        run: grep -r --include "*.rs" --files-without-match "@generated" crates | xargs rustfmt --check --config="skip_children=true"
        working-directory: ./compiler/

  build-compiler:
    name: Build Rust Compiler (${{ matrix.target.os }})
    strategy:
      matrix:
        target:
          - target: x86_64-unknown-linux-musl
            os: ubuntu-latest
            build-name: relay
            artifact-name: relay-bin-linux-x64
            packages: musl-tools
            features: vendored
          - target: aarch64-unknown-linux-musl
            os: ubuntu-latest
            build-name: relay
            artifact-name: relay-bin-linux-arm64
            features: vendored
            cross: true
          - target: x86_64-apple-darwin
            os: macos-latest
            build-name: relay
            artifact-name: relay-bin-macos-x64
          - target: aarch64-apple-darwin
            os: macos-latest
            build-name: relay
            artifact-name: relay-bin-macos-arm64
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            build-name: relay.exe
            artifact-name: relay-bin-win-x64
    runs-on: ${{ matrix.target.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.72.0
          override: true
          target: ${{ matrix.target.target }}
      - uses: actions/setup-node@v2
        if: github.event_name == 'push' && github.repository == 'facebook/relay' && github.ref == 'refs/heads/main'
        with:
          node-version: 16.x
          cache: 'yarn'
      - name: Install dependencies
        if: github.event_name == 'push' && github.repository == 'facebook/relay' && github.ref == 'refs/heads/main'
        run: yarn install --frozen-lockfile --ignore-scripts
      - name: Set the compiler version when releasing the `main` branch
        if: github.event_name == 'push' && github.repository == 'facebook/relay' && github.ref == 'refs/heads/main'
        run: yarn gulp setCompilerMainVersion
        env:
          RELEASE_COMMIT_SHA: ${{ github.sha }}
      - name: Install packages
        if: matrix.target.os == 'ubuntu-latest' && matrix.target.packages
        run: sudo apt install ${{ matrix.target.packages }} -y
      - name: Install cross
        if: matrix.target.cross
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cross
      # Current published version of cross only works correctly if run from compiler directory
      # See related issue https://github.com/cross-rs/cross/issues/615
      # actions-rs/cargo@v1 does not support this option https://github.com/actions-rs/cargo/pull/59
      # Either we need to install cross from git or manually run cargo / cross instead of using action
      - name: Build project
        working-directory: compiler
        run: ${{ matrix.target.cross && 'cross' || 'cargo' }} build --release --target ${{ matrix.target.target }} ${{ matrix.target.features && '--features' }} ${{ matrix.target.features }}
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.target.artifact-name }}
          path: compiler/target/${{ matrix.target.target }}/release/${{ matrix.target.build-name }}
